### ISSUE TITLE
NullPointerException in Eclipse Oxygen

### ISSUE THREAD

**Issue by gabor-farkas** [projectlombok/lombok#1443]
Generally, using SneakyThrows and NonNull in anonymous classes cause the eclipse compiler to throw NullPointerExceptions.
The smallest reproduction I could figure out so far is to have a fresh 'Java' eclipse oxygen, using JDK7 as the workspace default JDK, create a new standard Java project and add two classes
```java
package x;

import lombok.SneakyThrows;

public class A {
	
	public static final Function<String, String> F = new Function<String, String>() {
		@Override
		@SneakyThrows
		public String apply(String folder) {
			return null;
		}
	};
	
	public interface Function<A, B> {
		B apply(A a);
	}
	
}
```
and
```java
package b;

import x.A;

public class B {
	
	public static void main(String[] args) {
		A.F.apply("");
	}

}
```
In the Error Log view I see:
```
java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.flow.ExceptionHandlingFlowContext.<init>(ExceptionHandlingFlowContext.java:101)
	at org.eclipse.jdt.internal.compiler.flow.ExceptionHandlingFlowContext.<init>(ExceptionHandlingFlowContext.java:83)
	at org.eclipse.jdt.internal.compiler.ast.TryStatement.analyseCode(TryStatement.java:135)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.analyseCode(MethodDeclaration.java:125)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:739)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:211)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.analyseCode(QualifiedAllocationExpression.java:133)
	at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.analyseCode(FieldDeclaration.java:90)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:685)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:263)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.analyseCode(CompilationUnitDeclaration.java:118)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:873)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:141)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gabor-farkas** [comment]
(it occurs with 1.16.18, the current latest)

**Comment by nbali** [comment]
Still happening with Eclipe Photon.

**Comment by nbali** [comment]
(@gabor-farkas IMO you can rename it to "NullPointerException in Eclipse")
