### ISSUE TITLE
[BUG] Code doesn't compile with `val` in some cases

### ISSUE THREAD

**Issue by sergewar** [projectlombok/lombok#2462]
**Describe the bug**
Code with `val` don't compile with additional brackets. If change `val` to `final var` it compiles without errors

**To Reproduce**
```
private void df() {
        val typesForTesting = List.of("B", "R", "AR", "MB");
        val blaSetting = "bla-id.%s.%s.enabled";
        val someConstant = "GHJKJHG";
// works
        setSet("ahaha", "true");
// works
        setSet(("ahaha"), "true");
// works
        typesForTesting
                .forEach(type -> setSet("bla", "true"));
// works
        typesForTesting
                .forEach(type -> setSet(("bla"), "true"));
// works
        typesForTesting
                .forEach(type -> setSet(String.format(blaSetting, type, someConstant), "true"));

// doesn't work
        typesForTesting
                .forEach(type -> setSet((String.format(blaSetting, type, someConstant)), "true"));
    }

    private void setSet(String a, String b) {
    }
```

Stack trace
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project test-cases: Compilation failure
An exception has occurred in the compiler (11.0.1). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: Incorrect number of arguments; expected 2, found 0
	at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:162)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:636)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1634)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:454)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.visitLambda(TransTypes.java:540)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1807)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:454)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translateArgs(TransTypes.java:212)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:639)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1634)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:454)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.visitExec(TransTypes.java:599)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1452)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:167)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1020)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:454)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.visitMethodDef(TransTypes.java:489)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:866)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:139)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:918)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:475)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:774)
	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:454)
	at jdk.compiler/com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:942)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1553)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1432)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1516)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1432)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)

```

**Expected behavior**
Code should be compiled without error

**Version info (please complete the following information):**
 - Lombok version 1.18.12
 - Platform MacOS 10.14.6  
java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

**Comment by sergewar** [comment]
looks like https://github.com/rzwitserloot/lombok/issues/2460 pointed to the same problem
