### ISSUE TITLE
[BUG] Eclipse Save Action Crash - @Getter + @Setter / @Data in combination with action "Use "this" qualifier for field accesses"

### ISSUE THREAD

**Issue by remonvv** [projectlombok/lombok#2608]
**Describe the bug**
Eclipse Save Action Crash - `@Getter`+`@Setter` or `@Data` in combination with action either "Use "this" qualifier for field accesses" or "Use "this" qualifier for method accesses". Eclipse throws an error when the "Use "this" qualifier for field accesses" is configured to "Only if necessary". In other words, only if they are both set to "Always" will no error be thrown.
```
A save participant caused problems.
  The save participant 'Code Clean Up' caused an exception: org.eclipse.text.edits.MalformedTreeException: Overlapping text edits. See the error log for details.
```

**To Reproduce**

1. Install latest Eclipse version (does not appear to be Eclipse version related but tested in 2020-03 and 2020-09)
2. Install lombok 1.18.14 for aforementioned eclipse version
3. Preferences -> Java -> Editor -> Save Actions -> Enable "Perform the selected actions on save" -> Enable "Additional actions"
4. "Configure..." -> Member Accesses -> Enable "Use "this" qualifer for field (or member, or both) accesses -> Select "Only if necessary"
5. Add POJO annotated with either `@Getter` and `@Setter`, or just `@Data` with at least 2 fields (no error with just 1 field)
6. Attempt to save file

Minimal code to reproduce :

```
package default;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Test {
	private String one;
	private String two;
}
```

**Expected behavior**
No error on save.

**Version info (please complete the following information):**
 - 1.18.xx
 - Eclipse 2020-xx / javac 15

**Additional context**
Issue also reproducible in Spring Tools Suit 4. Note that a similar error is thrown when you enable the action "Use local variable type inference (Java 10 or higher)" although that appears to be a separate issue. To reproduce that simply add any field that would trigger `var` type inference in the accessors. Only by selecting "Always" for both access actions and disabling the type inference selection can get to a workable situation.

**Comment by remonvv** [comment]
I just noticed enabling the action "Use local variable type inference (Java 10 or higher)" causes the same issue even with the qualifer access settings set to "Always" so there seem to be more general issues. Don't have time to chase other repros at the moment I'm afraid. For now selecting "Only if necessary" on field accesses and disabling the type inference action seems to result in a workable situation.

**Comment by Rawi01** [comment]
I am unable to reproduce this issue using the latest eclipse and lombok version. As it is impossible to use the latest release in eclipse right now you most likely use an older version and this one is fixed already.

**Comment by remonvv** [comment]
I'm not sure what to tell you. Ironically I tried my very own reproduction path on a different computer with the latest Eclipse drop 
```
Eclipse IDE for Java Developers (includes Incubating components)

Version: 2020-09 (4.17.0)
Build id: 20200910-1200
```
And it fails to even compile the sample class with 
```
Errors occurred during the build.
Errors running builder 'Java Builder' on project 'issue-2608'.
lombok/launch/PatchFixesHider$Transform
```
This is with zero adjustments to the default configuration. I'm using this POM :
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>lombokreproduction</groupId>
	<artifactId>issue-2608</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>lombokreproduction-issue-2608</name>
	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.14</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>
```
And the aforementioned test class in the ticket. I created the test class prior to installing Lombok which saved fine. Post install Eclipse cannot even open the editor due to the above error.

Note that this is separate from the original issue which is reproducible still on an STS4 fresh install 
```
Spring Tool Suite 4 

Version: 4.8.0.RELEASE
Build Id: 202009151856
```
Both the original issue and this is on a Win10 Pro environment although it's hard to imagine that affects anything.

**Comment by remonvv** [comment]
Reproduction GIF on fresh eclipse with fresh lombok :

![issue-2608](https://user-images.githubusercontent.com/516951/96031569-d39d9780-0e5d-11eb-9368-fc01034883ad.gif)

**Comment by Rawi01** [comment]
Thanks for the fast answer and the additional information.

For eclipse you have to update the lombok version by hand, changing the version in your `pom.xml` only affects the maven build. You can check the currently used lombok version if you scroll down a little bit in the about dialog. To update lombok simply replace the `lombok.jar` in your eclipse directory.

Unfortunately the latest lombok release does not work in eclipse (because of the `lombok/launch/PatchFixesHider$Transform` error) so it is not possible for you to test if the original issue is already fixed or not. Some of these `Overlapping text edits` errors are hard to reproduce and a single character can change everything.

**Comment by remonvv** [comment]
Yes I know the POM version and the installed version are two separate dependencies to manage. I believe the above reproduction was with the highest lombok version not causing the transform error installed and as shown the latest pom. I have tested with matching versions with the same result.

I'll await an update on this. I assume there's no robust workaround at the moment? Thanks for the response.

**Comment by sfussenegger** [comment]
I've now received this exception a bunch after installing the latest edge version in my Eclipse installation as I was hoping for a fix of what I believe is #3886

> Eclipse IDE for Java Developers (includes Incubating components)
> 
> Version: 2025-06 (4.36.0)
> Build id: 20250605-1316

My installation currently contains these files named `*lombok*` (with a conspicuous version conflict):

```
$ find . -name '*lombok*'
./plugins/org.projectlombok.agent_1.18.38
./plugins/org.projectlombok.agent_1.18.38/lombok.jar
./plugins/org.springframework.tooling.boot.ls_1.63.0.202506052016/servers/spring-boot-language-server/lib/lombok-1.18.36.jar
./plugins/org.springframework.tooling.boot.ls_1.63.0.202506052016/servers/spring-boot-language-server/lib/rewrite-java-lombok-8.42.5.jar
./features/org.projectlombok.feature_1.18.38
```

My Cleanup settings in `./.settings/org.eclipse.jdt.ui.prefs` (needed to add `.txt` suffix for the upload): [org.eclipse.jdt.ui.prefs](https://github.com/user-attachments/files/21931625/org.eclipse.jdt.ui.prefs.txt)

And here's the stacktrace:

```
!ENTRY org.eclipse.jdt.ui 4 10006 2025-08-22 08:35:55.766
!MESSAGE The save participant 'org.eclipse.jdt.ui.postsavelistener.cleanup' caused an exception: org.eclipse.text.edits.MalformedTreeException: Overlapping text edits
!STACK 0
org.eclipse.text.edits.MalformedTreeException: Overlapping text edits
	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:126)
	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:1)
	at java.base/java.util.Collections.indexedBinarySearch(Collections.java:335)
	at java.base/java.util.Collections.binarySearch(Collections.java:323)
	at org.eclipse.text.edits.TextEdit.computeInsertionIndex(TextEdit.java:799)
	at org.eclipse.text.edits.TextEdit.internalAdd(TextEdit.java:784)
	at org.eclipse.text.edits.TextEdit.addChild(TextEdit.java:340)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.addEdit(ASTRewriteAnalyzer.java:340)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doTextRemove(ASTRewriteAnalyzer.java:412)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doTextRemoveAndVisit(ASTRewriteAnalyzer.java:420)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.rewriteRequiredNode(ASTRewriteAnalyzer.java:921)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2885)
	at org.eclipse.jdt.core.dom.Assignment.accept0(Assignment.java:299)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:455)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:461)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:476)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:3128)
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:134)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:431)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:469)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:463)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:476)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2464)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:126)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:455)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:461)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:476)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2370)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:652)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3312)
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.internalRewriteAST(ASTRewrite.java:306)
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.rewriteAST(ASTRewrite.java:295)
	at org.eclipse.jdt.internal.corext.refactoring.structure.CompilationUnitRewrite.attachChange(CompilationUnitRewrite.java:290)
	at org.eclipse.jdt.internal.corext.refactoring.structure.CompilationUnitRewrite.createChange(CompilationUnitRewrite.java:252)
	at org.eclipse.jdt.internal.corext.fix.CompilationUnitRewriteOperationsFixCore.createChange(CompilationUnitRewriteOperationsFixCore.java:126)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.calculateChange(CleanUpRefactoring.java:799)
	at org.eclipse.jdt.internal.corext.fix.CleanUpPostSaveListener.saved(CleanUpPostSaveListener.java:384)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider$4.run(CompilationUnitDocumentProvider.java:1610)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider.notifyPostSaveListeners(CompilationUnitDocumentProvider.java:1604)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider.commitWorkingCopy(CompilationUnitDocumentProvider.java:1388)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider$3.execute(CompilationUnitDocumentProvider.java:1463)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider$DocumentProviderOperation.run(TextFileDocumentProvider.java:133)
	at org.eclipse.ui.actions.WorkspaceModifyDelegatingOperation.execute(WorkspaceModifyDelegatingOperation.java:71)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:112)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2457)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2482)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
	at org.eclipse.ui.internal.editors.text.WorkspaceOperationRunner.run(WorkspaceOperationRunner.java:76)
	at org.eclipse.ui.internal.editors.text.WorkspaceOperationRunner.run(WorkspaceOperationRunner.java:66)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider.executeOperation(TextFileDocumentProvider.java:461)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider.saveDocument(TextFileDocumentProvider.java:783)
	at org.eclipse.ui.texteditor.AbstractTextEditor.performSave(AbstractTextEditor.java:5020)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.performSave(CompilationUnitEditor.java:1262)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.doSave(CompilationUnitEditor.java:1316)
	at org.eclipse.ui.texteditor.AbstractTextEditor$TextEditorSavable.doSave(AbstractTextEditor.java:7260)
	at org.eclipse.ui.Saveable.doSave(Saveable.java:213)
	at org.eclipse.ui.internal.SaveableHelper.doSaveModel(SaveableHelper.java:317)
	at org.eclipse.ui.internal.SaveableHelper.lambda$1(SaveableHelper.java:195)
	at org.eclipse.ui.internal.SaveableHelper.lambda$3(SaveableHelper.java:261)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:433)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$7(WorkbenchWindow.java:2335)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2332)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:268)
	at org.eclipse.ui.internal.SaveableHelper.saveModels(SaveableHelper.java:206)
	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:150)
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3819)
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3832)
	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:81)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:277)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:320)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:581)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:662)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:451)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:104)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1963)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1655)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1682)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1665)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1704)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:1000)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:4013)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:923)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2639)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6857)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6169)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1605)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4519)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:678)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:583)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:185)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:219)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:149)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:467)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:627)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1431)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1403)
```

Let me know if I can provide more information!

**Comment by rzwitserloot** [comment]
@sfussenegger Cannot reproduce.

I installed current HEAD in my own eclipse:

```
Version: 2025-03 (4.35.0)
Build id: 20250306-0812
```

Then went to the global preferences, filtered on "Save actions":

checked 'Perform selected actions on save', check 'Additional actions', hit the 'Configure... button', tab 'Member accesses',

check both of the "Use 'this' qualifier' and set em both to 'Only if necessary', and for kicks, in tab 'Missing code', 'add missing annotations, `@Override`" just to check if things are working.

Then write this source file:

```java
import lombok.Data;

@Data
public class Test {
	final String field;
	
	void foo(int field) {
		System.out.println(field);
		System.out.println(this.field);
	}
	
	public String toString() {
		System.out.println(this.getField());
		return "Hi";
	}
}
```

Then hit 'save', I get no errors and the save actions are applied:

* `toString` gains an `@Override`.
* The `this` in front of `this.getField()` disappears.
* The `this` in front of `this.field` remains, as it is necessary.

We'll need many more instructions as to how to reproduce this issue in order to pick it up.
