### ISSUE TITLE
[BUG] Eclipse UI freezes after Save Actions

### ISSUE THREAD

**Issue by JanecekPetr** [projectlombok/lombok#2818]
**Describe the bug**
With Save actions enabled in eclipse, I'm getting massive UI freezes on bigger files.

**To Reproduce**
UI Freeze of 114 seconds, stack trace:
```
Stack Trace
	at java.base@15.0.2/java.io.WinNTFileSystem.getLength(Native Method)
	at java.base@15.0.2/java.io.File.length(File.java:988)
	at org.eclipse.jdt.internal.core.util.Util.getResourceContentsAsCharArray(Util.java:1206)
	at org.eclipse.jdt.internal.core.CompilationUnit.getContents(CompilationUnit.java:680)
	at lombok.eclipse.handlers.EclipseHandlerUtil.getDocComment(EclipseHandlerUtil.java:2696)
	at lombok.eclipse.handlers.EclipseHandlerUtil$CopyJavadoc.applySetter(EclipseHandlerUtil.java:2779)
	at lombok.eclipse.handlers.EclipseHandlerUtil$CopyJavadoc.access$3(EclipseHandlerUtil.java:2777)
	at lombok.eclipse.handlers.EclipseHandlerUtil$CopyJavadoc$3.apply(EclipseHandlerUtil.java:2761)
	at lombok.eclipse.handlers.EclipseHandlerUtil.copyJavadoc(EclipseHandlerUtil.java:2827)
	at lombok.eclipse.handlers.EclipseHandlerUtil.copyJavadoc(EclipseHandlerUtil.java:2807)
	at lombok.eclipse.handlers.HandleSetter.createSetter(HandleSetter.java:262)
	at lombok.eclipse.handlers.HandleSetter.createSetter(HandleSetter.java:198)
	at lombok.eclipse.handlers.HandleSetter.createSetterForField(HandleSetter.java:182)
	at lombok.eclipse.handlers.HandleSetter.generateSetterForField(HandleSetter.java:111)
	at lombok.eclipse.handlers.HandleSetter.generateSetterForType(HandleSetter.java:89)
	at lombok.eclipse.handlers.HandleData.handle(HandleData.java:69)                  <<---- All stack traces are the same up until now
	at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:106)
	at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
	at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnType(TransformEclipseAST.java:267)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:107)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:74)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:69)
	at lombok.eclipse.EclipseAST.traverse(EclipseAST.java:224)
	at lombok.eclipse.TransformEclipseAST.go(TransformEclipseAST.java:224)
	at lombok.eclipse.TransformEclipseAST.transform(TransformEclipseAST.java:185)
	at lombok.eclipse.TransformEclipseAST.transform_swapped(TransformEclipseAST.java:110)
	at jdk.internal.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
	at java.base@15.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@15.0.2/java.lang.reflect.Method.invoke(Method.java:564)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:129)
	at lombok.launch.PatchFixesHider$Transform.transform_swapped(PatchFixesHider.java:213)
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:11687)
	at org.eclipse.jdt.internal.core.util.CommentRecorderParser.endParse(CommentRecorderParser.java:135)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12880)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13104)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13061)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:11448)
	at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:337)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.accept(CompilationUnitResolver.java:186)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.accept(CompilationUnitResolver.java:181)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:342)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:276)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:551)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:623)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInImports(CompilationUnitScope.java:452)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:525)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1233)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:712)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1205)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:820)
	at org.eclipse.jdt.internal.corext.fix.CleanUpPostSaveListener.createAst(CleanUpPostSaveListener.java:596)
	at org.eclipse.jdt.internal.corext.fix.CleanUpPostSaveListener.saved(CleanUpPostSaveListener.java:373)
```

I have tens of these. I can do a JFR recording if that helps in any way. If this is not sufficient, I'll gladly provide a reproducing package. Until then, just enable some Save actions (Organize Imports seems to be particularly nasty) and Lombok away!

**Expected behavior**
I expect the operation to save file not to take two minutes while blocking the UI thread.

**Version info (please complete the following information):**
 - Lombok version: 1.18.16
 - Platform: eclipse 2021-03 (4.19), Build id: I20210303-1800
 - Windows 10

**Comment by Rawi01** [comment]
I think I already fixed that one in #2809. There is no edge release with this patch at the moment so I have uploaded a [pre-built version](https://github.com/projectlombok/lombok/files/6369283/lombok.zip) for you.

**Comment by JanecekPetr** [comment]
You, sir, are a scholar and a gentleman. Thank you!

**Comment by JanecekPetr** [comment]
(I'll test it out and potentially close this on Sunday evening.)

**Comment by JanecekPetr** [comment]
This is great, thank you. Previously with a single Save Action I was getting 120-ish second long saves, now with a lot of Save Actions a save on a humongous file takes a second or two, and is unnoticeable on normal files.
