### ISSUE TITLE
[BUG] Lombok fails to run due to ClassNotFoundException: HandleBuilderRemove

### ISSUE THREAD

**Issue by Nightfirecat** [projectlombok/lombok#2828]
**Describe the bug**
While building [runelite/runelite at commit `5b12bcc907f9ce7c0ebf963fa8bc1d990152250f`](https://github.com/runelite/runelite/tree/5b12bcc907f9ce7c0ebf963fa8bc1d990152250f), which uses Lombok 1.18.20 as a dependency, I get the following error *only when using my configured IntelliJ run configuration* (not while building on the command line or in IntelliJ):

```
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:34:8
java: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.RuntimeException: java.lang.ClassNotFoundException: lombok.javac.handlers.HandleBuilderRemove
  	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:114)
  	at lombok.javac.HandlerLibrary.loadAnnotationHandlers(HandlerLibrary.java:181)
  	at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:166)
  	at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:47)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:96)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:124)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:177)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:73)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:686)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:786)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:881)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1335)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:231)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:514)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:560)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:512)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:355)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:280)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:234)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1464)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1101)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1247)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1066)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:832)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:419)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:183)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:301)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:132)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:219)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  	at java.base/java.lang.Thread.run(Thread.java:829)
  Caused by: java.lang.ClassNotFoundException: lombok.javac.handlers.HandleBuilderRemove
  	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
  	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:530)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  	at java.base/java.lang.Class.forName0(Native Method)
  	at java.base/java.lang.Class.forName(Class.java:398)
  	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
  	... 39 more
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:36:16
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:37:16
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:38:14
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:39:21
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:40:18
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:41:15
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:42:20
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:43:20
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:44:19
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:45:18
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:46:22
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:47:21
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:48:18
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:49:17
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:50:20
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:51:19
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:52:20
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:53:18
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:54:16
java: constructor InstanceTemplates in enum net.runelite.api.InstanceTemplates cannot be applied to given types;
  required: no arguments
  found: int,int,int,int,int
  reason: actual and formal argument lists differ in length
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:101:34
java: cannot find symbol
  symbol:   method getPlane()
  location: variable template of type net.runelite.api.InstanceTemplates
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:102:37
java: cannot find symbol
  symbol:   method getBaseX()
  location: variable template of type net.runelite.api.InstanceTemplates
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:102:64
java: cannot find symbol
  symbol:   method getBaseX()
  location: variable template of type net.runelite.api.InstanceTemplates
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:102:86
java: cannot find symbol
  symbol:   method getWidth()
  location: variable template of type net.runelite.api.InstanceTemplates
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:103:37
java: cannot find symbol
  symbol:   method getBaseY()
  location: variable template of type net.runelite.api.InstanceTemplates
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:103:64
java: cannot find symbol
  symbol:   method getBaseY()
  location: variable template of type net.runelite.api.InstanceTemplates
/home/nightfirecat/Documents/git/runelite/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java:103:86
java: cannot find symbol
  symbol:   method getHeight()
  location: variable template of type net.runelite.api.InstanceTemplates
```

The file in question is a small enum annotated with `@AllArgsConstructor` which can be viewed here: https://github.com/runelite/runelite/blob/5b12bcc907f9ce7c0ebf963fa8bc1d990152250f/runelite-api/src/main/java/net/runelite/api/InstanceTemplates.java

**To Reproduce**
See above.

**Expected behavior**
This would run without error.

**Version info (please complete the following information):**
 - Lombok version: 1.18.20
 - Platform: javac 11.0.11

**Additional context**
According to other contributors to the linked project, this is not an issue present on all systems. Additionally, this issue only occurred for me following [commit `e70a92d9770d1f781c2e3b4de635aa87b9222c08`](https://github.com/runelite/runelite/commit/e70a92d9770d1f781c2e3b4de635aa87b9222c08) where, among other things, [we upgraded Lombok from version 1.18.4 to 1.18.20](https://github.com/runelite/runelite/commit/e70a92d9770d1f781c2e3b4de635aa87b9222c08#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L42).

**Comment by Rawi01** [comment]
This seems to be a configuration problem, `HandleBuilderRemove` was added in `1.18.16` so most likely there are multiple lombok versions in your classpath at the same time.

**Comment by Nightfirecat** [comment]
As far as I'm able to tell, we use only the single version of lombok in the project, using the same version number via a provided-scope dependency or by referencing a shared version number variable. A cursory `rg -B4 -A4 -txml lombok` doesn't reveal any outliers that I can see.

**Comment by Nightfirecat** [comment]
It seems this was caused by some issue with my local repository. Deleting `~/.m2` and reimporting all needed dependencies afterward led to my unchanged run config working fine.
