### ISSUE TITLE
[BUG] Exception while resolving: NODE LOCAL because "that.type" is null

### ISSUE THREAD

**Issue by adrian-herscu** [projectlombok/lombok#2839]
**Describe the bug**
```
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ qa-tester-utils ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 82 source files to C:\projects\system-testing\qa-tester-utils\target\classes
Exception while resolving: NODE LOCAL (class com.sun.tools.javac.tree.JCTree$JCVariableDecl) @val
final ___Lombok_VAL_Attrib__ object = actualIterator.next()(SimpleFileObject[C:\projects\system-testing\qa-tester-utils\src\main\java\com\ge\acutecare\qa\tester\utils\StreamMatchersExtensions.java])
java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.hasTag(com.sun.tools.javac.code.TypeTag)" because "that.type" is null
	at jdk.compiler/com.sun.tools.javac.comp.Check$Validator.visitTypeIdent(Check.java:1489)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCPrimitiveTypeTree.accept(JCTree.java:2484)
	at jdk.compiler/com.sun.tools.javac.comp.Check$Validator.validateTree(Check.java:1508)
	at jdk.compiler/com.sun.tools.javac.comp.Check.validate(Check.java:1379)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitVarDef(Attr.java:1288)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:983)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:671)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:745)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:764)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1442)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1047)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:671)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:745)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1232)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:893)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:671)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:745)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5330)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5221)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5057)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitClassDef(Attr.java:974)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:790)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:671)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:745)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitAnonymousClassDefinition(Attr.java:2840)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitNewClass(Attr.java:2731)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1800)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:671)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitReturn(Attr.java:2308)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1657)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:671)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:745)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:764)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1442)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1047)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:671)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:745)
	at lombok.javac.JavacResolution.attrib(JavacResolution.java:249)
	at lombok.javac.JavacResolution.memberEnterAndAttribute(JavacResolution.java:217)
	at lombok.javac.JavacResolution.resolveMethodMember(JavacResolution.java:165)
	at lombok.javac.handlers.HandleVal.endVisitLocal(HandleVal.java:144)
	at lombok.javac.JavacNode.traverse(JavacNode.java:122)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:126)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:126)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:105)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:95)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:126)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:126)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:105)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:95)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:90)
	at lombok.javac.JavacAST.traverse(JavacAST.java:218)
	at lombok.javac.HandlerLibrary.callASTVisitors(HandlerLibrary.java:276)
	at lombok.javac.JavacTransformer.transform(JavacTransformer.java:64)
	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:328)
	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:187)
	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:241)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:90)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1025)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:940)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1269)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1384)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1261)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:935)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:190)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Lombok visitor handler class lombok.javac.handlers.HandleVal failed: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.hasTag(com.sun.tools.javac.code.TypeTag)" because "that.type" is null
[INFO] 1 error

```

**To Reproduce**
```
    <!-- NOTE: same happens with 16 -->
    <java.version>14</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <maven.compiler.release>${java.version}</maven.compiler.release>
```
```
      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>1.18.20</version>
        <scope>provided</scope>
      </dependency>
```
```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
          <configuration>
            <!-- NOTE: same happens without this section -->
            <annotationProcessorPaths>
              <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.20</version>
              </path>
            </annotationProcessorPaths>
          </configuration>
        </plugin>
```

**Expected behavior**
Project should compile and open without errors both in IntelliJ and Eclipse.

**Version info (please complete the following information):**
 - Lombok version 1.18.20
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse.
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\212600552\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7142.45\plugins\maven\lib\maven3
Java version: 16.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-16.0.1
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
**Additional context**
Same project compiles with Java 8 and opens fine both in IntelliJ aand Eclipse.
Seems related to 
https://github.com/projectlombok/lombok/issues/2681
although the error is different.

**Comment by adrian-herscu** [comment]
```
            protected boolean matchesSafely(final Stream<T> actual) {
                if (matchers.isEmpty()
                    && !actual.findAny().isPresent()) {
                    return true;
                }

                accumulator = new LinkedList<>();
                val actualIterator = actual.iterator();
                var index = 0;
                while (actualIterator.hasNext()) {
                    val object = actualIterator.next();
                    accumulator.add(object);

                    if (matchers.get(index).matches(object)) {
                        index += 1;
                        if (index >= matchers.size())
                            return true;
                    }
                }
                return false;
            }
```

Both val instances trigger the bug.
