### ISSUE TITLE
[BUG] Eclipse: 'Building' has encountered a problem

### ISSUE THREAD

**Issue by velo** [projectlombok/lombok#2958]
**Describe the bug**
When trying to build a project, all I get is this error popup.

![Screen Shot 2021-09-15 at 16 22 45](https://user-images.githubusercontent.com/136590/133370245-836f6d81-7873-42ce-86b4-3895ed2a9b94.png) 

After that, all I see are compilation errors due to some code that should be generated, not been there.

Full stack from error logs down bellow.

**To Reproduce**
I'm using a fresh eclipse install, with a project that make heavy usage of Lombok annotations

If I click on `Project/Clean...` I can see this happening every time

**Expected behavior**
Project builds and constructors, getters, and all other generated code to be generated.

**Version info (please complete the following information):**
 - Lombok version: 1.18.12 and 1.18.20
 - Java version: openJDK 16.0.2
 - Eclipse version: 2021-06 (4.20.0)
 - OS: macOS bigsur 11.5.2 x64

**Additional context**

Working fine when using gradle/command line

Full stack trace:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.Binding.setAnnotations(org.eclipse.jdt.internal.compiler.lookup.AnnotationBinding[], boolean)" because "this.recipient" is null
	at org.eclipse.jdt.internal.compiler.ast.Annotation.resolveType(Annotation.java:978)
	at org.eclipse.jdt.internal.compiler.ast.ArrayInitializer.resolveTypeExpecting(ArrayInitializer.java:231)
	at org.eclipse.jdt.internal.compiler.ast.MemberValuePair.resolveTypeExpecting(MemberValuePair.java:75)
	at org.eclipse.jdt.internal.compiler.ast.Annotation.resolveType(Annotation.java:968)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.resolveAnnotations(ASTNode.java:942)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.resolveAnnotations(ASTNode.java:775)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.initAnnotationTagBits(SourceTypeBinding.java:1610)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getAnnotationTagBits(SourceTypeBinding.java:1600)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.checkAnnotationsInType(SourceTypeBinding.java:1100)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:1114)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:533)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:895)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by rzwitserloot** [comment]
I can't fix this without knowing what's in your source file. I'm guessing either `@Delegate` or `val` is involved, in combination with another lombok feature, perhaps `@SneakyThrows`.

I'll have to close this without action without more information - will wait until 2021-09-30.

**Comment by velo** [comment]
Not sure what it was, but, I started fresh, install eclipse fresh, installed lombok fresh and boom gone.
