### ISSUE TITLE
[BUG] Compilation failure with @Singular on JDK 17

### ISSUE THREAD

**Issue by gwallet** [projectlombok/lombok#2980]
**Describe the bug**
Hi,
I'm facing an issue when compiling code annotated with Lombok on freshly released Java 17 compiler.

**To Reproduce**
Here is a sample Java source file that failed to compile:
```
import java.util.List;
import lombok.Builder;
import lombok.Singular;

@Builder
public class Example {
  @Singular private List<Object> things;
}
```

Then compile this file with the following command:
```
> /path/to/jvm17/javac -cp /path/to/lombok.jar Example.java
```

Got the following error:
```
An exception has occurred in the compiler (17). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.NullPointerException: Cannot read field "bindingsWhenTrue" because "currentBindings" is null
	at jdk.compiler/com.sun.tools.javac.comp.Attr.handleSwitch(Attr.java:1791)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitSwitch(Attr.java:1586)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1294)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:674)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:748)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:767)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1445)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:674)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:748)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1235)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:921)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:674)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:748)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5474)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5365)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5196)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitClassDef(Attr.java:977)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:819)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:674)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:748)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5474)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5365)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5196)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attrib(Attr.java:5141)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1317)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

**Expected behavior**
The compilation should proceed like it does with JDK < 17

**Version info (please complete the following information):**
 - Lombok version 1.18.20 (latest release at the time of writing this)
 - OpenJDK 17 freshly installed with dnf on Linux Fedora 33
 - Same behaviour with the JDK 17 downloaded as tgz from Oracle download page.

**Additional context**
No additional context.

**Comment by celcius112** [comment]
Hello @gwallet, I think this issue is fixex in the latest edge version : https://github.com/projectlombok/lombok/issues/2963

**Comment by chrisgleissner** [comment]
I can confirm that it is. I had the very same issue and the edge release 1.8.21 resolves it.

**Comment by paveljandejsek** [comment]
Any idea when new stable version with this might be released? (just wondering if its worth it to go to edge version for a while or not)
