### ISSUE TITLE
[BUG] Error compiling @Getter annotation with onMethod_ where inner annotation contains braces

### ISSUE THREAD

**Issue by Medo42** [projectlombok/lombok#3003]
**Describe the bug**
When compiling the following code with lombok 1.18.22, a compilation error occurs:

    @Getter(onMethod_ = @Bar(value = {"bar"}))
    private String foo;

Compiling the same code without the braces in the "value" property succeeds:

    @Getter(onMethod_ = @Bar(value = "bar"))
    private String foo;

Both variants compile successfully with lombok 1.18.20.

Compiling with Lombok 1.18.22 yields the following error:

    medo@medo:~/git/minimum-gwt-lombok-example/src/main/java$ javac -cp ~/.m2/repository/org/projectlombok/lombok/1.18.22/lombok-1.18.22.jar ExampleFile.java
    java.lang.NullPointerException
            at lombok.javac.handlers.JavacHandlerUtil$3.scan(JavacHandlerUtil.java:1823)
            at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.visitNewArray(TreeScanner.java:251)
            at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewArray.accept(JCTree.java:1745)
            at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
            at lombok.javac.handlers.JavacHandlerUtil$3.scan(JavacHandlerUtil.java:1824)
            at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.visitAssign(TreeScanner.java:269)
            at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1878)
            at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
            at lombok.javac.handlers.JavacHandlerUtil$3.scan(JavacHandlerUtil.java:1824)
            at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
            at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.visitAnnotation(TreeScanner.java:358)
            at lombok.javac.handlers.JavacHandlerUtil$3.visitAnnotation(JavacHandlerUtil.java:1848)
            at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2572)
            at lombok.javac.handlers.JavacHandlerUtil.clearTypes(JavacHandlerUtil.java:1821)
            at lombok.javac.handlers.JavacHandlerUtil.unboxAndRemoveAnnotationParameter(JavacHandlerUtil.java:1811)
            at lombok.javac.handlers.HandleGetter.handle(HandleGetter.java:145)
            at lombok.javac.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:113)
            at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:256)
            at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnField(JavacTransformer.java:84)
            at lombok.javac.JavacNode.traverse(JavacNode.java:135)
            at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
            at lombok.javac.JavacNode.traverse(JavacNode.java:100)
            at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
            at lombok.javac.JavacNode.traverse(JavacNode.java:95)
            at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
            at lombok.javac.JavacNode.traverse(JavacNode.java:90)
            at lombok.javac.JavacAST.traverse(JavacAST.java:218)
            at lombok.javac.JavacTransformer.transform(JavacTransformer.java:63)
            at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:328)
            at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:187)
            at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:241)
            at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:90)
            at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
            at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:896)
            at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)
            at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1335)
            at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
            at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
            at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
            at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
            at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
            at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
    ExampleFile.java:6: error: cannot find symbol
        @lombok.Getter(onMethod_ = @Bar(value = {"bar"}))
                       ^
      symbol:   method onMethod_()
      location: @interface Getter
    error: Lombok annotation handler class lombok.javac.handlers.HandleGetter failed on ExampleFile.java: java.lang.NullPointerException
    2 errors

**To Reproduce**

Here is the complete ExampleFile.java:

    @interface Bar {
        String[] value() default {};
    }
    
    public class ExampleFile {
        @lombok.Getter(onMethod_ = @Bar(value = {"bar"}))
        private String foo;
    }

**Expected behavior**
Compilation succeeds and Lombok generates a method like

    @Bar(value = {"bar"})
    public String getFoo() {
        return foo;
    }

**Version info**
 - Lombok 1.18.22
 - javac 11.0.10

**Comment by trangntt-016** [comment]
Hi @Medo42 ,

I'm interested in this bug. Could you please assign this to me? Thanks

**Comment by Medo42** [comment]
Hi, I'm not part of the project and so I can't assign bugs. If you just want to be notified of new developments you can subscribe to the bug, but if you want to work on fixing it you'll have to talk to someone else.

**Comment by trangntt-016** [comment]
Hi @rzwitserloot,

Just wondering if you could assign this bug to me?

**Comment by Rawi01** [comment]
@trangntt-016 Unfortunately I missed this issue and your comment and fixed this for the duplicate #3040. If you are still interested in contributing to lombok feel free to pick any other issue and let me know if I should assign it to you.
