### ISSUE TITLE
[BUG] NullpointerException when compiling @Builder annotated classes with jdk6 

### ISSUE THREAD

**Issue by salmen** [projectlombok/lombok#3043]
Hello,
I'am getting a NullPointerException when trying to compile with jdk6 classes having @Builder annotation.

**To Reproduce**
create dto.java  : `package testlombockj6;

import lombok.Builder;

@Builder
public class dto {

}
`
compile : jdk1.6.0_31/bin/javac.exe -cp lombok-1.18.22.jar dto.java

`error: Lombok annotation handler class lombok.javac.handlers.HandleBuilder failed on dto.java: java.lang.NullPointerException
java.lang.NullPointerException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at lombok.javac.Javac.storeEnd(Javac.java:395)
        at lombok.javac.handlers.JavacHandlerUtil.setGeneratedBy(JavacHandlerUtil.java:178)
        at lombok.javac.handlers.JavacHandlerUtil.recursiveSetGeneratedBy(JavacHandlerUtil.java:163)
        at lombok.javac.handlers.HandleConstructor.createConstructor(HandleConstructor.java:356)
        at lombok.javac.handlers.HandleConstructor.generate(HandleConstructor.java:244)
        at lombok.javac.handlers.HandleConstructor.generateConstructor(HandleConstructor.java:211)
        at lombok.javac.handlers.HandleBuilder.handle(HandleBuilder.java:301)
        at lombok.javac.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:113)
        at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:256)
        at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnType(JavacTransformer.java:79)
        at lombok.javac.JavacNode.traverse(JavacNode.java:132)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
        at lombok.javac.JavacNode.traverse(JavacNode.java:95)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
        at lombok.javac.JavacNode.traverse(JavacNode.java:90)
        at lombok.javac.JavacAST.traverse(JavacAST.java:218)
        at lombok.javac.JavacTransformer.transform(JavacTransformer.java:63)
        at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:328)
        at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:187)
        at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:241)
        at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:90)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:627)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:556)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:701)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:987)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:727)
        at com.sun.tools.javac.main.Main.compile(Main.java:353)
        at com.sun.tools.javac.main.Main.compile(Main.java:279)
        at com.sun.tools.javac.main.Main.compile(Main.java:270)
        at com.sun.tools.javac.Main.compile(Main.java:69)
        at com.sun.tools.javac.Main.main(Main.java:54)
`

Note: compilation works fine with jdk1.8 . I'am wondering if jdk1.6 is still supported by Lombok ? Is there any compatibility matrix ?

**Version info (please complete the following information):**
 - Lombok version 1.18.22
 - Platform JDK 1.6

Regards

**Comment by Rawi01** [comment]
As far as I know Java 6 is still supported. There are also test for it and they all pass but the test system uses some magic to do that so it possible that a regular compiler call is still broken. According to the stacktrace the end position map is `null` for some reason. Adding a `null` check is easy but I first need a way to reproduce the problem. 
The `javac` compiler comments also mention that it is only set if you add `-Xjcov` as compiler parameter, can you try that?

**Comment by Rawi01** [comment]
I used a docker container to run the old compiler and can reproduce the problem. As expected a `null` check fixes the problem. I also tried the compiler flag and that seems to work too.

**Comment by salmen** [comment]
Adding -Xjcov resolves the issue, allthougth i can't figure out why ?! Also i couldn't find any official documentation about this option. I think that a null check is a better solution. Waiting for your PR @Rawi01. Thanks :)
