### ISSUE TITLE
[BUG] @Singular on Map with Annotation on Type Parameter in Java 17 Cause Compiler Error

### ISSUE THREAD

**Issue by ntroutman** [projectlombok/lombok#3177]
**Describe the bug**
When using Java 17 and combining @Builder with @Singular and an annotation on a Maps type parameters, a java compiler error is thrown:

```
An exception has occurred in the compiler (17). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writePosition(ClassWriter.java:672)
        at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writeTypeAnnotation(ClassWriter.java:649)
        at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writeTypeAnnotations(ClassWriter.java:553)
        at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writeCode(ClassWriter.java:1120)
        at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writeMethod(ClassWriter.java:988)
        at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writeMethods(ClassWriter.java:1479)
        at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writeClassFile(ClassWriter.java:1584)
        at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writeClass(ClassWriter.java:1505)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.genCode(JavaCompiler.java:738)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1617)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1585)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

**To Reproduce**

[FailingExampleWithSingular.java.txt](https://github.com/projectlombok/lombok/files/8508315/FailingExampleWithSingular.java.txt)

Fails:
` javac -cp lombok-1.18.22.jar FailingExampleWithSingular.java`

[PassingExample.java.txt](https://github.com/projectlombok/lombok/files/8508318/PassingExample.java.txt)

Passes:
`javac -cp lombok-1.18.22.jar PassingExample.java`

**Expected behavior**

Expect the code to compile with the annotations intact on the class.

**Version info (please complete the following information):**
 - Lombok version: 1.18.22

 - Platform: javac version: javac 17

**Comment by Rawi01** [comment]
This is a JDK 14-17.0.1 bug (https://github.com/projectlombok/lombok/issues/2434) and fixed JDK 17.0.2 and 18. There is no workaround in lombok for older versions.
