### ISSUE TITLE
[BUG] NoSuchAlgorithmException during Eclipse Installation with Oomph setup containing Lombok setupTask

### ISSUE THREAD

**Issue by mcrocker** [projectlombok/lombok#3255]
**Describe the bug**
When installing Eclipse 4.24 (2022-06) using JDK 11.0.15+10, and an Oomph Installation setup that includes the org.projectlombok.feature.feature.group requirement, Installation fails and produces a stack trace that includes:

> [2022-09-01 10:55:06] ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
>   at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:291)
>   at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:551)
>   at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:343)
>   at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:899)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3828)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3756)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3737)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3630)
>   at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.installPerform(SimpleVariablePage.java:1343)
>   at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.access$33(SimpleVariablePage.java:1211)
>   at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage$20.run(SimpleVariablePage.java:1156)
>   ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=_home_up000054_eclipse_autozoneecom-2022-06 - JEE_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
>   ERROR: org.eclipse.equinox.p2.engine code=0 Error with signed content.
>   java.security.NoSuchAlgorithmException: An error occurred while processing the signatures for the file: /home/up000054/.p2/pool/plugins/org.projectlombok.agent_1.18.24
>     at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent(SignedBundleHook.java:231)
>     at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.checkCertificates(CertificateChecker.java:77)
>     at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.start(CertificateChecker.java:58)
>     at org.eclipse.equinox.internal.p2.engine.phases.CheckTrust.completePhase(CheckTrust.java:55)
>     at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:254)
>     at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
>     at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
>     at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:80)
>     at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:48)
>     at org.eclipse.equinox.internal.provisional.p2.director.PlanExecutionHelper.executePlan(PlanExecutionHelper.java:46)
>     at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:547)
>     at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:343)
>     at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:899)
>     at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3828)
>     at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3756)
>     at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3737)
>     at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3630)
>     at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.installPerform(SimpleVariablePage.java:1343)
>     at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.access$33(SimpleVariablePage.java:1211)
>     at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage$20.run(SimpleVariablePage.java:1156)
>   Caused by: java.security.NoSuchAlgorithmException: No algorithm found for 2.16.840.1.101.3.4.3.2
>     at org.eclipse.osgi.internal.signedcontent.PKCS7Processor.findEncryption(PKCS7Processor.java:95)
>     at org.eclipse.osgi.internal.signedcontent.PKCS7Processor.processSignerInfos(PKCS7Processor.java:364)
>     at org.eclipse.osgi.internal.signedcontent.PKCS7Processor.<init>(PKCS7Processor.java:172)
>     at org.eclipse.osgi.internal.signedcontent.SignatureBlockProcessor.processSigner(SignatureBlockProcessor.java:109)
>     at org.eclipse.osgi.internal.signedcontent.SignatureBlockProcessor.process(SignatureBlockProcessor.java:76)
>     at org.eclipse.osgi.internal.signedcontent.SignedBundleFile.initializeSignedContent(SignedBundleFile.java:56)
>     at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent(SignedBundleHook.java:223)
>     at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.checkCertificates(CertificateChecker.java:77)
>     at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.start(CertificateChecker.java:58)
>     at org.eclipse.equinox.internal.p2.engine.phases.CheckTrust.completePhase(CheckTrust.java:55)
>     at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:254)
>     at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
>     at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
>     at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:80)
>     at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:48)
>     at org.eclipse.equinox.internal.provisional.p2.director.PlanExecutionHelper.executePlan(PlanExecutionHelper.java:46)
>     at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:547)
>     at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:343)
>     at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:899)
>     at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3828)
>     at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3756)
>     at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3737)
>     at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3630)
>     at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.installPerform(SimpleVariablePage.java:1343)
>     at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.access$33(SimpleVariablePage.java:1211)

**To Reproduce**
Install using the [Eclipse Installer](https://wiki.eclipse.org/Eclipse_Installer) (version 1.18.0 Build 4828) and JDK 11.0.15+10 selecting a user product that is based on the [Eclipse IDE for Enterprise Java and Web Developers](https://www.eclipse.org/downloads/packages/release/2022-06/r/eclipse-ide-enterprise-java-and-web-developers) (2022-06) installation product with an additional P2 Director for Lombok:

```XML
<setupTask
	xsi:type="setup.p2:P2Task"
	label="lombok-site">
	<requirement
		name="org.projectlombok.feature.feature.group"
		versionRange="[1.18.24,1.18.24]" />
	<repository
		url="http://projectlombok.org/p2/"/>
	<description>Project Lombok</description>
</setupTask>
```

and follow through the normal installation process clicking Next and Finish buttons as needed.

When the process gets to the Lombok feature, it will generate an error and fail to install Eclipse. In simple install mode, clicking the log link in the error message or in advanced mode a stack trace featuring the example above will be displayed due to the inability to verify the Lombok package signature with the built-in certificate authorities.

**Expected behavior**
The installation _should_ succeed and produce a running installation of the Eclipse IDE that includes the Lombok feature.

**Version info (please complete the following information):**
 - Lombok version: 1.18.24 "Envious Ferret"
 - Platform:
    - javac version: 11.0.15
    - Eclipse Installer: 1.18.0 Build 4828 ([2020-09](https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2020-09/R/eclipse-inst-linux64.tar.gz))
       - This is the last version of the installer that will run on Java 8, though 11 was used here,
    - Eclipse:
       - Version: 2022-06 (4.24.0)
          - This is the last version that will work on Java 11,
       - Build id: 20220609-1112
    - OS: CentOS Linux release 7.8.2003

**Additional context**
When installed manually by a user, the Project Lombok feature can be installed, but requires the user to accept the certificate in a separate dialog.

** Work-Around**

If the requirement includes attributes to indicate that it is optional and non-greedy, then the installer will successfully add the Lombok site to Eclipse, but NOT install the feature. Then the user can manually install it without having to add the site to Eclipse. This is marginally better than forcing the user to install it entirely manually.

```xml
<!-- Signing errors prevent fully automated install. Optional, non-greedy, adds site, but still requires manual install -->
<setupTask
	xsi:type="setup.p2:P2Task"
	label="lombok-site">
	<requirement
		name="org.projectlombok.feature.feature.group"
		optional="true"
		greedy="false"
		versionRange="[1.18.24,1.18.24]" />
	<repository
		url="http://projectlombok.org/p2/"/>
	<description>Project Lombok</description>
</setupTask>
```

**Comment by mcrocker** [comment]
It seems that newer versions of the Eclipse installer, such as 2022-06, which must be run with Java 11+, now handle the signing certificate approval process at the installation level, so the Lombok feature can be included as with default options (non-optional and greedy) and successfully installed as long as the person doing the installation is comfortable trusting the Lombok signing certificate in the dialog that pops up during the install. 

For users stuck with Java 8, this may still be a problem, but the work-around in the description may help a little bit.
