### ISSUE TITLE
[BUG] Lombok is not compatible with the logback-core version

### ISSUE THREAD

**Issue by kunlong-luo** [projectlombok/lombok#3271]
**Describe the bug** 
When I use the @Slf4j  annotation for unit testing, I get an error.

**To Reproduce**
```java
@Slf4j
class DemoTest {
    @Test
    void demo() {
        log.debug("demo");
    }
}
```

**Expected behavior**
The output should be `2022-10-01 08:25:04.195 DEBUG   --- [           main] com.loongstudio.coder.util.DemoTest      : demo`.

**Version info (please complete the following information):**
 - Lombok version 1.18.24
 - logback-classic 1.4.1
 - logback-core 1.2.11
 - All platforms

**Additional context**
```java
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String ch.qos.logback.core.util.EnvUtil.logbackVersion()'
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:81)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:77)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:50)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:152)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:422)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:408)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.loongstudio.coder.util.DemoTest.<clinit>(DemoTest.java:13)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.intellij.junit5.JUnit5TestRunnerUtil.loadMethodByReflection(JUnit5TestRunnerUtil.java:148)
	at com.intellij.junit5.JUnit5TestRunnerUtil.buildRequest(JUnit5TestRunnerUtil.java:130)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by janrieke** [comment]
That's not a Lombok issue. You can see in your stacktrace that the code Lombok generates successfully calls `org.slf4j.LoggerFactory.getLogger`. The exception appears later. It's probably a dependency or configuration issue.

**Comment by kunlong-luo** [comment]
Thank you. I think I've solved that problem, The solution is to upgrade the `logback-core` to version `1.4.1`
