### ISSUE TITLE
[BUG] javac compile fails on specific usage of @ExtensionMethod, but without any useful detail

### ISSUE THREAD

**Issue by erizzo** [projectlombok/lombok#3362]
I use @ExtnsionMethod sparingly, but in some cases javac compilation (via Gradle) fails with the error below. Note that it is just a java.lang.AssertionError with no details.

`error: Lombok annotation handler class lombok.javac.handlers.HandleExtensionMethod failed on /home/xxx/xxx/src/main/java/com/zxxx/xxx/xxx/MyClass.java: java.lang.AssertionError`

I've changed the project/package/class names to protect the innocent.

The stack trace is enormous, here is the top portion:

```
java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:126)
	at com.sun.tools.javac.comp.Resolve.resolveSelf(Resolve.java:3404)
	at com.sun.tools.javac.comp.Attr.selectSym(Attr.java:3399)
	at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3278)
	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)
	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.visitReturn(Attr.java:1686)
	at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1384)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1124)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
	at lombok.javac.JavacResolution.attrib(JavacResolution.java:258)
	at lombok.javac.JavacResolution.memberEnterAndAttribute(JavacResolution.java:221)
	at lombok.javac.JavacResolution.resolveMethodMember(JavacResolution.java:169)
	at lombok.javac.handlers.HandleExtensionMethod$ExtensionMethodReplaceVisitor.handleMethodCall(HandleExtensionMethod.java:174)
	at lombok.javac.handlers.HandleExtensionMethod$ExtensionMethodReplaceVisitor.visitMethodInvocation(HandleExtensionMethod.java:155)
	at lombok.javac.handlers.HandleExtensionMethod$ExtensionMethodReplaceVisitor.visitMethodInvocation(HandleExtensionMethod.java:1)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:77)
	at com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:255)
	at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1390)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:77)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:162)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:77)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:144)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:77)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
	at lombok.javac.handlers.HandleExtensionMethod$ExtensionMethodReplaceVisitor.replace(HandleExtensionMethod.java:149)
	at lombok.javac.handlers.HandleExtensionMethod.handle(HandleExtensionMethod.java:93)
	at lombok.javac.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:113)
	at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:256)
	at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnType(JavacTransformer.java:79)
	at lombok.javac.JavacNode.traverse(JavacNode.java:132)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:95)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:90)
	at lombok.javac.JavacAST.traverse(JavacAST.java:218)
	at lombok.javac.JavacTransformer.transform(JavacTransformer.java:63)
	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:328)
	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:187)
	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:241)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:90)
	at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        <... lots of gradle stuff below here...>
```
If I remove the @ExtensionMethod and call the method in the convnetional way, everything compiles fine.
Unfortunately I can't narrow it down to a small reproducible case; I use @ExtensionMethod in plenty of other places without problems.

**Comment by Rawi01** [comment]
If it is not reproducible we cannot fix the problem. 

If the extension methode always fails you can simply share the method signature. If the same extension method works in a different place then you should focus on the using class. I guess that you already identified the problematic method call, if not you can simply replace method invocations until it works. The last one you removed causes the exception. Add it back and remove more code until it starts working again. That way you should be able to create a smaller example that you can share. In some cases the method parameters are important too (e.g. lambdas can cause some problems).
