### ISSUE TITLE
[BUG] Lombok plugin not work with Android Studio Hedgehog and Giraffe

### ISSUE THREAD

**Issue by jrjohn** [projectlombok/lombok#3574]
**Describe the bug**
log keyword couldn't be identified by IDE.

**To Reproduce**

Lombok version [233.13135.65]

1.Put lombok.jar file to /Applications/Android Studio Hedgehog .app/Contents/plugins
2.Run Android Studio and open the android java project.
**Expected behavior**

**Version info (please complete the following information):**
 - Lombok version [233.13135.65]
 - Android Studio Hedgehog | 2023.1.1

Build #AI-231.9392.1.2311.11076708, built on November 10, 2023
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 4
Metal Rendering is ON
Registry:

    external.system.auto.import.disabled=true

    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:

    com.guowenlong.dimens (3.1.0)

**Additional context**
![image](https://github.com/projectlombok/lombok/assets/6859844/ec6dc43c-0fce-4b2d-9914-8ac750ac125d)
`
java.lang.NoClassDefFoundError: com/intellij/util/concurrency/ThreadingAssertions
	at de.plushnikov.intellij.plugin.util.LombokLibraryUtil.hasLombokLibrary(LombokLibraryUtil.java:39)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:106)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$collectAugments$3(PsiAugmentProvider.java:134)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:257)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:133)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.calcMethods(ClassInnerStuffCache.java:143)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.lambda$getMethods$1(ClassInnerStuffCache.java:51)
	at com.intellij.psi.util.CachedValuesManager.lambda$getProjectPsiDependentCache$0(CachedValuesManager.java:134)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:244)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:244)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getProjectPsiDependentCache(CachedValuesManager.java:132)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:51)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:281)
	at de.plushnikov.intellij.plugin.extension.LombokFieldFindUsagesHandlerFactory.canFindUsages(LombokFieldFindUsagesHandlerFactory.java:35)
	at com.intellij.find.findUsages.FindUsagesManager.getFindUsagesHandler(FindUsagesManager.java:160)
	at com.intellij.find.actions.ShowUsagesAction.startFindUsages(ShowUsagesAction.java:247)
	at com.intellij.find.actions.ShowUsagesAction$1.handlePsi(ShowUsagesAction.java:219)
	at com.intellij.find.actions.PsiTargetVariant.handle(resolver.kt:72)
	at com.intellij.find.actions.ResolverKt.findShowUsages(resolver.kt:50)
	at com.intellij.find.actions.ShowUsagesAction.showUsages(ShowUsagesAction.java:195)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.showUsages(GotoDeclarationOrUsageHandler2.kt:91)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.invoke(GotoDeclarationOrUsageHandler2.kt:72)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$0(CodeInsightAction.java:68)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:74)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:155)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:65)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:40)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.actionPerformed(GotoDeclarationAction.java:70)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.processEvent(IdeMouseEventDispatcher.java:269)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:253)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:614)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.concurrency.ThreadingAssertions PluginClassLoader(plugin=PluginDescriptor(name=Lombok, id=Lombook Plugin, descriptorPath=plugin.xml, path=/Applications/Android Studio Hedgehog .app/Contents/plugins/lombok.jar, version=233.13135.65, package=null, isBundled=true), packagePrefix=null, instanceId=23, state=active)
	... 71 more

`

**Comment by dstango** [comment]
The Intellij plugin is provided and maintaind by Jetbrains. I'd suggest you report the issue there.

BTW: Jetbrains has removed the lombok plugin from the Intellij community distribution somewhen this year, so Intellij requires to install the plugin explicitly. Don't know about Android Studio, but maybe it's similar.

**Comment by jrjohn** [comment]
I have reported this to Jetbrains. Thank you very much.
