### ISSUE TITLE
[FEATURE] Add support for Eclipse 2024-03 (4.31)

### ISSUE THREAD

**Issue by Rawi01** [projectlombok/lombok#3620]
**Describe the feature**
While working on a fix for broken Javadoc in Eclipse, I realised that I needed to add new patches for the upcoming Eclipse release. There also seem to be some changes that might affect the handling of string literals and delegate methods. I created this issue to track the fixed stuff and allow everyone to report additional problems in the same place.

**Describe the target audience**
Everyone who wants to use Eclipse 2024-03 (release date is 13.03.2024).

**Latest pipeline build**
[lombok.jar](https://github.com/projectlombok/lombok/actions/runs/8256670904/artifacts/1320428636)

**Comment by famod** [comment]
FTR, I suppose this is one of those issues:
```
Lombok annotation handler class lombok.eclipse.handlers.HandleToString failed
java.lang.NoSuchMethodError: 'java.lang.StringBuffer org.eclipse.jdt.internal.compiler.ast.Expression.print(int, java.lang.StringBuffer)'
  	at lombok.eclipse.handlers.EclipseHandlerUtil.createAnnotation(EclipseHandlerUtil.java:1335)
  	at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:105)
  	at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
  	at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnType(TransformEclipseAST.java:265)
  	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:107)
  	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
  	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:74)
  	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
  	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:69)
  	at lombok.eclipse.EclipseAST.traverse(EclipseAST.java:224)
  	at lombok.eclipse.TransformEclipseAST.go(TransformEclipseAST.java:222)
  	at lombok.eclipse.TransformEclipseAST.transform(TransformEclipseAST.java:183)
  	at lombok.eclipse.TransformEclipseAST.transform_swapped(TransformEclipseAST.java:107)
  	at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        [...]
```

@Rawi01 there's a typo in the issue title: 2024-04 -> 2024-03 :slightly_smiling_face:

**Comment by Rawi01** [comment]
@famod Ups, fixed. This error is already fixed in the latest [edge release](https://projectlombok.org/download-edge).

**Comment by famod** [comment]
Good to know, thanks!

**Comment by c-koell** [comment]
@Rawi01 thanks for the patch !
For me it seems that the pipeline build contains other fixes like https://github.com/projectlombok/lombok/issues/3529
The edge release does not contain this particular fix.

Hopyfully a official release is coming soon .. thanks

**Comment by dpolivaev** [comment]
Please fix it. Urgently. I have to rollback my eclipse now.

**Comment by chrylis** [comment]
Eclipse 4.31 is rolling out, so a release with the Eclipse fix (which works for me!) would be appreciated.

**Comment by ksanjeev9211** [comment]
lombok.jar version linked to the opening message fixed it for me also.
I was getting issues with 'Accessors(fluent=true)'

**Comment by jdimeo** [comment]
Yay for a strong community around Lombok that it gets dogpiled the moment it breaks :-)

**Comment by mgsCatDev** [comment]
Its a shame not to have more support when all is running ok, but, eh, this way you know you are important. Deep, very deep inside our developments, Lombok it's an indispensable part.
Long live Lombok!

**Comment by odrotbohm** [comment]
I also still see a compile error when using `@__(…)` on the edge builds. The actual error message is "__ cannot be resolved to a type".

<img width="890" alt="Screenshot 2024-03-18 at 10 22 49" src="https://github.com/projectlombok/lombok/assets/128577/47a8349f-9035-4f93-b9e7-3cac1a60005c">

**Comment by rspilker** [comment]
This is part of the latest [edge release](https://projectlombok.org/download-edge), all feedback is welcome.

**Comment by nlisker** [comment]
With Eclipse Version: 2024-03 (4.31) and Lombok 1.18.32, the following gives an error:
```java
@FieldDefaults(level = AccessLevel.PRIVATE)
public class A{}
```
Lombok visitor handler class lombok.eclipse.handlers.HandleFieldDefaults failed - See error log.

Not sure where the error log is, but it should be easy enough to reproduce.
---

By the way, there is a discrepancy between the Lombok version shown in the installation details
![image](https://github.com/projectlombok/lombok/assets/37422899/37df07cb-a5e0-491a-a9af-7641dbec2196)
and the one shown in the About section
![image](https://github.com/projectlombok/lombok/assets/37422899/f194a0b8-1e1f-4886-94f6-fe435f9ae455)

**Comment by danthe1st** [comment]
@nlisker You can view the error log using `Window`>`Show View`>`Error Log`.

**Comment by nlisker** [comment]
I looked, the error doesn't appear there.

**Comment by MichaelNesterenko** [comment]
I experience issues with 1.8.32 version within vscode:
 
```
Apr 5, 2024, 3:52:00 PM Lombok annotation handler class lombok.eclipse.handlers.HandleBuilder failed
'void org.eclipse.jdt.internal.compiler.ast.CaseStatement.<init>(org.eclipse.jdt.internal.compiler.ast.Expression, int, int)'
java.lang.NoSuchMethodError: 'void org.eclipse.jdt.internal.compiler.ast.CaseStatement.<init>(org.eclipse.jdt.internal.compiler.ast.Expression, int, int)'
	at lombok.eclipse.Eclipse.createCaseStatement(Eclipse.java:285)
	at lombok.eclipse.handlers.singulars.EclipseJavaUtilListSingularizer.appendBuildCode(EclipseJavaUtilListSingularizer.java:75)
	at lombok.eclipse.handlers.HandleBuilder.generateBuildMethod(HandleBuilder.java:821)
	at lombok.eclipse.handlers.HandleBuilder.handle(HandleBuilder.java:563)
	at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:106)
	at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
	at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnType(TransformEclipseAST.java:269)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:107)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:74)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:74)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:69)
	at lombok.eclipse.EclipseAST.traverse(EclipseAST.java:224)
	at lombok.eclipse.TransformEclipseAST.go(TransformEclipseAST.java:226)
	at lombok.eclipse.TransformEclipseAST.transform(TransformEclipseAST.java:187)
	at lombok.eclipse.TransformEclipseAST.transform_swapped(TransformEclipseAST.java:104)
	at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:146)
	at lombok.launch.PatchFixesHider$Transform.transform_swapped(PatchFixesHider.java:272)
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:11535)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12736)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12966)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12923)
	at org.eclipse.jdt.internal.compiler.parser.SourceTypeConverter.convert(SourceTypeConverter.java:154)
	at org.eclipse.jdt.internal.compiler.parser.SourceTypeConverter.buildCompilationUnit(SourceTypeConverter.java:99)
	at org.eclipse.jdt.internal.core.hierarchy.HierarchyResolver.resolve(HierarchyResolver.java:741)
	at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.buildForProject(IndexBasedHierarchyBuilder.java:252)
	at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.buildFromPotentialSubtypes(IndexBasedHierarchyBuilder.java:337)
	at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.build(IndexBasedHierarchyBuilder.java:153)
	at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.compute(TypeHierarchy.java:323)
	at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.refresh(TypeHierarchy.java:1281)
	at org.eclipse.jdt.internal.core.CreateTypeHierarchyOperation.executeOperation(CreateTypeHierarchyOperation.java:94)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:805)
	at org.eclipse.jdt.internal.core.SourceType.newTypeHierarchy(SourceType.java:954)
	at org.eclipse.jdt.internal.core.SourceType.newTypeHierarchy(SourceType.java:911)
	at org.eclipse.jdt.internal.corext.refactoring.structure.ChangeSignatureProcessor.getCachedTypeHierarchy(ChangeSignatureProcessor.java:718)
	at org.eclipse.jdt.internal.corext.refactoring.structure.ChangeSignatureProcessor.checkInitialConditions(ChangeSignatureProcessor.java:737)
	at org.eclipse.jdt.internal.corext.refactoring.code.IntroduceParameterRefactoring.checkInitialConditions(IntroduceParameterRefactoring.java:220)
	at org.eclipse.jdt.ls.core.internal.text.correction.RefactorProposalUtility.getIntroduceParameterRefactoringProposals(RefactorProposalUtility.java:914)
	at org.eclipse.jdt.ls.core.internal.corrections.RefactorProcessor.getIntroduceParameterProposals(RefactorProcessor.java:172)
	at org.eclipse.jdt.ls.core.internal.corrections.RefactorProcessor.getProposals(RefactorProcessor.java:158)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:187)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:765)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
 
looks like error is exposed when `@Singular` annotation is used:
 
```
@Data
    @Builder
    public static class References {
        @Singular
        private List<Reference> references;
    }
```

**Comment by nlisker** [comment]
@MichaelNesterenko Not sure about VScode, but with Eclipse there's this problem: https://github.com/projectlombok/lombok/issues/3621. See if you can do a manual installation since they the automatic one seems to have a problem for some people.

**Comment by MichaelNesterenko** [comment]
@nlisker, vscode manages plugin installation internally. From what I see issue is with the specific annotation processing, not with plugin itself

**Comment by gjevardat** [comment]
Thanks the version provided fixes the issue.
I notice version is documented as 1.18.31 in eclipse About Window. Is it expected ?
Also any  idea of a release date ?
Thanks :)

**Comment by janrieke** [comment]
No. You probably installed an outdated edge build. Use [the latest v1.18.32 release](https://projectlombok.org/download), it includes this fix.

**Comment by gjevardat** [comment]
> No. You probably installed an outdated edge build. Use [the latest v1.18.32 release](https://projectlombok.org/download), it includes this fix.

Ok thanks it works.

**Comment by cassiobastos** [comment]
After upgrading to Eclipse Version: 2024-06 (4.32.0) Build id: 20240606-1231, the bug is still there, even going to v1.18.32 as suggested. Please see
[.log](https://github.com/user-attachments/files/15876884/default.log)

**Comment by skyblackhawk** [comment]
1.18.36 version have same bug.
