### ISSUE TITLE
[BUG] StackOverflowError in Eclipse in Synchronize view

### ISSUE THREAD

**Issue by yuriypalych** [projectlombok/lombok#3654]
**Describe the bug**
I have two open local Eclipse projects for the same Git repositories, but in different Git branches. Today I run "Team -> Synchronize Workspace" command for both of them at the same time. Usually it works without any issues, but today I received "Background Indexer Crash Recovery" popup window and java.lang.StackOverflowError in the logs:

**Stacktrace:**

!ENTRY org.eclipse.jdt.core 4 4 2024-04-15 10:14:35.725
!MESSAGE Background Indexer Crash Recovery
!STACK 0
java.lang.StackOverflowError
    at lombok.eclipse.EclipseAST.buildTree(EclipseAST.java:367)
    at lombok.eclipse.EclipseAST.buildTree(EclipseAST.java:1)
    at lombok.core.AST.buildWithField0(AST.java:394)
    at lombok.core.AST.buildWithField(AST.java:292)
    at lombok.eclipse.EclipseAST.drill(EclipseAST.java:532)
    at lombok.eclipse.EclipseAST.buildStatement(EclipseAST.java:527)
    at lombok.eclipse.EclipseAST.buildTree(EclipseAST.java:367)
    at lombok.eclipse.EclipseAST.buildTree(EclipseAST.java:1)
    at lombok.core.AST.buildWithField0(AST.java:394)
    at lombok.core.AST.buildWithField(AST.java:292)
    at lombok.eclipse.EclipseAST.drill(EclipseAST.java:532)
    at lombok.eclipse.EclipseAST.buildStatement(EclipseAST.java:527)

**Version info:**
- org.projectlombok.agent_1.18.32
- Eclipse 4.31
- Windows 11

I found two very similar issues: https://github.com/projectlombok/lombok/issues/3610, https://github.com/projectlombok/lombok/issues/3302

**Comment by Rawi01** [comment]
Have you tried the workarounds (`-Xss`, split long method chain) mentioned in your linked issues?
