### ISSUE TITLE
[BUG]  ArrayIndexOutOfBoundsException using Eclipse

### ISSUE THREAD

**Issue by gnagflowsemad** [projectlombok/lombok#3659]
I tried using Eclipse with Linux and Lombok. When I try to start my Application with Lombok annotations, I get an error message popup while building:

Errors occurred during the build.
Errors running builder 'Java Builder' on project 'my-project'.
java.lang.ArrayIndexOutOfBoundsException

My configuration:
Linux Fedora 39, openjdk 22.0.1 2024-04-16, Eclipse IDE for Java Developers (Version: 2024-03 (4.31.0))
installed Lombok via lombok.jar and Install new software...
tried Eclipse Platform, Eclipse STS and Eclipse for Java Developers

Lombok appears in About Dialog:
Lombok v1.18.32 "Envious Ferret" is installed.

Did always a complete Eclipse restart.
Tried Java 17, 21, 22

I am unable to get my Application running. Runs fine with Maven and Intellij.

Thank you !

**Comment by Rawi01** [comment]
Please add a stacktrace or a reproducer

**Comment by gnagflowsemad** [comment]
Issue only appears after installing Lombok in Eclipse

java.lang.ArrayIndexOutOfBoundsException: Index -8 out of bounds for length 1
	at org.eclipse.jdt.internal.compiler.codegen.StackMapFrame.addStackItem(StackMapFrame.java:87)
	at org.eclipse.jdt.internal.compiler.ClassFile.traverse(ClassFile.java:7627)
	at org.eclipse.jdt.internal.compiler.ClassFile.generateStackMapTableAttribute(ClassFile.java:5480)
	at org.eclipse.jdt.internal.compiler.ClassFile.completeCodeAttribute(ClassFile.java:1703)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:406)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:325)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:759)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:829)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:414)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:840)

![Bildschirmfoto vom 2024-04-21 18-50-40](https://github.com/projectlombok/lombok/assets/147550706/35f3936f-f33d-492d-b12a-24a85ea5bca1)

**Comment by rtron-24** [comment]
can you show me code and more details. Like Code Details and structure of your project. It would be better if you can share a screencast

**Comment by gnagflowsemad** [comment]
Of course, uploaded a screencast
[Bildschirmaufzeichnung vom 2024-04-22, 20-10-23.webm](https://github.com/projectlombok/lombok/assets/147550706/97d4bc54-3323-49d1-9154-efc18551c216)

**Comment by Rawi01** [comment]
Thanks for adding all that information. I noticed that there is an additional exception in your error log, can you also share that one?

Can you also describe why you think that the problem is related to lombok? Lombok seems to work and the stacktrace only contain eclipse compiler classes.

**Comment by rtron-24** [comment]
I suggest to remove all lombok annotators and write getters setters and Constructors.  Make dummy ones if you are not using currently. Then Rebuild the project. If there are errors. Its with eclispse or other part of code. OtherWise we can check in lombok
