### ISSUE TITLE
[BUG] Potential NPE in EclipseHandlerUtil.setDocComment(..)

### ISSUE THREAD

**Issue by andi-huber** [projectlombok/lombok#3706]
Seeing stacktraces in Eclipse's Error Log

```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "compilationUnit" is null
	at lombok.eclipse.handlers.EclipseHandlerUtil.setDocComment(EclipseHandlerUtil.java:2841)
	at lombok.eclipse.handlers.EclipseHandlerUtil.setDocComment(EclipseHandlerUtil.java:2830)
	at lombok.eclipse.handlers.HandleConstructor.generateConstructorJavadoc(HandleConstructor.java:609)
	at lombok.eclipse.handlers.HandleConstructor.generate(HandleConstructor.java:290)
	at lombok.eclipse.handlers.HandleConstructor.generateConstructor(HandleConstructor.java:246)
	at lombok.eclipse.handlers.HandleBuilder.handle(HandleBuilder.java:359)
	at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:106)
	at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
	at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnType(TransformEclipseAST.java:269)
```

I don't have spent time to provide a reproducible example. However, the mitigation seems trivial. E.g. adding a null guard like

```java
ICompilationUnit compilationUnit = cud.compilationResult.compilationUnit;
if (compilationUnit == null) return; // add null guard, line 2841 in EclipseHandlerUtil
```

**Version info:**
 - Lombok 1.18.34
 - Platform Eclipse 4.32 (Release)

**Comment by famod** [comment]
Same here. I seems the issue comes from (perfectly legal) Javadoc of members in `@Builder` classes.

Hi @Rawi01, I'm under the impression that #3669 broke a few things (see also #3688).

**Comment by smil2k** [comment]
Removing javadoc from the class and the methods resolves the problem at my end.
