### ISSUE TITLE
[BUG]  loader constraint violation: when resolving method

### ISSUE THREAD

**Issue by gaojun121381** [projectlombok/lombok#3737]
at org.apache.flink.client.program.PackagedProgramUtils.generateException(PackagedProgramUtils.java:264)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:172)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)
	at org.apache.streampark.flink.client.trait.FlinkClientTrait$class.getJobGraph(FlinkClientTrait.scala:247)
	at org.apache.streampark.flink.client.impl.YarnSessionClient$.doSubmit(YarnSessionClient.scala:116)
	at org.apache.streampark.flink.client.trait.FlinkClientTrait$class.submit(FlinkClientTrait.scala:123)
	at org.apache.streampark.flink.client.impl.YarnSessionClient$.submit(YarnSessionClient.scala:41)
	at org.apache.streampark.flink.client.FlinkClientHandler$.submit(FlinkClientHandler.scala:40)
	at org.apache.streampark.flink.client.FlinkClientHandler.submit(FlinkClientHandler.scala)
	... 17 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving interface method "org.apache.flink.connector.kafka.source.enumerator.initializer.OffsetsInitializer.committedOffsets(Lorg/apache/kafka/clients/consumer/OffsetResetStrategy;)Lorg/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializer;" the class loader (instance of org/apache/flink/util/ChildFirstClassLoader) of the current class, com/yzc/bigdata/flink/monitor/task/behaviorlog/BusinessAnalysisCountTask, and the class loader (instance of org/apache/streampark/flink/proxy/ChildFirstClassLoader) for the method's defining class, org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializer, have different Class objects for the type org/apache/kafka/clients/consumer/OffsetResetStrategy used in the signature
	at com.yzc.bigdata.flink.monitor.task.behaviorlog.BusinessAnalysisCountTask.main(BusinessAnalysisCountTask.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)
	... 24 more

**Comment by Rawi01** [comment]
This seems to be completly unrelated to lombok, it is not mentioned in the stacktrace. If you still think that this is a lombok issue please provide additional information that can be used to reproduce it.
