### ISSUE TITLE
[BUG] StackOverflowError when using lombok 1.18.36

### ISSUE THREAD

**Issue by nimo23** [projectlombok/lombok#3781]
**Describe the bug**
I upgraded from 1.18.34 (which worked fine) to 1.18.36 and now I get the following error in eclipse (Version: 2024-09 (4.33.0)) with java version 21:

Lombok has logged too many messages; to avoid memory issues, further lombok logs will be squelched for a while. Restart eclipse to start over.

```
java.lang.StackOverflowError
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:5000)
	at java.base/java.util.regex.Pattern$LazyLoop.match(Pattern.java:5142)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:5000)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4878)
	at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:4110)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4914)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4969)
	at java.base/java.util.regex.Pattern$LazyLoop.match(Pattern.java:5146)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:5000)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4878)
	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:4134)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4914)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4969)
	at java.base/java.util.regex.Pattern$LazyLoop.match(Pattern.java:5146)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:5000)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4878)
	at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:4110)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4914)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4969)
	at java.base/java.util.regex.Pattern$LazyLoop.match(Pattern.java:5146)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:5000)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4878)
	at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:4110)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4914)
	at java.base/
...
...
...
```

**Expected behavior**
No Stackoverflow Error

**Version info (please complete the following information):**
 - Lombok version: 1.18.36
 - Java version: openjdk version "21.0.2" 2024-01-16
 - Eclipse version: Version: 2024-09 (4.33.0)

**Comment by rspilker** [comment]
Hmm, no Lombok visible in the call stack... So you have any more information? Can you isolate the problem to a specific piece of source code?

**Comment by jmax01** [comment]
I have the same issue.

```

    /**
     * Realm representation.
     *
     * @param accessCodeLifespan                                        the access code lifespan
     * @param accessCodeLifespanLogin                                   the access code lifespan login
     * @param accessCodeLifespanUserAction                              the access code lifespan user action
     * @param accessTokenLifespan                                       the access token lifespan
     * @param accessTokenLifespanForImplicitFlow                        the access token lifespan for implicit flow
     * @param accountTheme                                              the account theme
     * @param actionTokenGeneratedByAdminLifespan                       the action token generated by admin lifespan
     * @param actionTokenGeneratedByUserLifespan                        the action token generated by user lifespan
     * @param adminEventsDetailsEnabled                                 the admin events details enabled
     * @param adminEventsEnabled                                        the admin events enabled
     * @param adminTheme                                                the admin theme
     * @param attributes                                                the attributes
     * @param authenticationFlows                                       the authentication flows
     * @param authenticatorConfigs                                      the authenticator configs
     * @param browserFlow                                               the browser flow
     * @param browserSecurityHeaders                                    the browser security headers
     * @param bruteForceProtected                                       the brute force protected
     * @param certificate                                               the certificate
     * @param clientAuthenticationFlow                                  the client authentication flow
     * @param clientOfflineSessionIdleTimeout                           the client offline session idle timeout
     * @param clientOfflineSessionMaxLifespan                           the client offline session max lifespan
     * @param clientScopeMappings                                       the client scope mappings
     * @param clientScopes                                              the client scopes
     * @param clientSessionIdleTimeout                                  the client session idle timeout
     * @param clientSessionMaxLifespan                                  the client session max lifespan
     * @param clients                                                   the clients
     * @param codeSecret                                                the code secret
     * @param components                                                the components
     * @param defaultDefaultClientScopes                                the default default client scopes
     * @param defaultGroups                                             the default groups
     * @param defaultLocale                                             the default locale
     * @param defaultOptionalClientScopes                               the default optional client scopes
     * @param defaultRole                                               the default role
     * @param defaultSignatureAlgorithm                                 the default signature algorithm
     * @param directGrantFlow                                           the direct grant flow
     * @param displayName                                               the display name
     * @param displayNameHtml                                           the display name html
     * @param duplicateEmailsAllowed                                    the duplicate emails allowed
     * @param editUsernameAllowed                                       the edit username allowed
     * @param emailTheme                                                the email theme
     * @param enabled                                                   the enabled
     * @param enabledEventTypes                                         the enabled event types
     * @param eventsEnabled                                             the events enabled
     * @param eventsExpiration                                          the events expiration
     * @param eventsListeners                                           the events listeners
     * @param failureFactor                                             the failure factor
     * @param federatedUsers                                            the federated users
     * @param groups                                                    the groups
     * @param id                                                        the id
     * @param identityProviderMappers                                   the identity provider mappers
     * @param identityProviders                                         the identity providers
     * @param internationalizationEnabled                               the internationalization enabled
     * @param loginTheme                                                the login theme
     * @param loginWithEmailAllowed                                     the login with email allowed
     * @param maxDeltaTimeSeconds                                       the max delta time seconds
     * @param maxFailureWaitSeconds                                     the max failure wait seconds
     * @param minimumQuickLoginWaitSeconds                              the minimum quick login wait seconds
     * @param notBefore                                                 the not before
     * @param oauth2DeviceCodeLifespan                                  the oauth 2 device code lifespan
     * @param oauth2DevicePollingInterval                               the oauth 2 device polling interval
     * @param offlineSessionIdleTimeout                                 the offline session idle timeout
     * @param offlineSessionMaxLifespan                                 the offline session max lifespan
     * @param offlineSessionMaxLifespanEnabled                          the offline session max lifespan enabled
     * @param otpPolicyAlgorithm                                        the otp policy algorithm
     * @param otpPolicyDigits                                           the otp policy digits
     * @param otpPolicyInitialCounter                                   the otp policy initial counter
     * @param otpPolicyLookAheadWindow                                  the otp policy look ahead window
     * @param otpPolicyPeriod                                           the otp policy period
     * @param otpPolicyType                                             the otp policy type
     * @param otpSupportedApplications                                  the otp supported applications
     * @param clientPolicies                                            the client policies
     * @param clientProfiles                                            the client profiles
     * @param passwordPolicy                                            the password policy
     * @param permanentLockout                                          the permanent lockout
     * @param privateKey                                                the private key
     * @param protocolMappers                                           the protocol mappers
     * @param publicKey                                                 the public key
     * @param quickLoginCheckMilliSeconds                               the quick login check milli seconds
     * @param realm                                                     the realm
     * @param refreshTokenMaxReuse                                      the refresh token max reuse
     * @param registrationAllowed                                       the registration allowed
     * @param registrationEmailAsUsername                               the registration email as username
     * @param registrationFlow                                          the registration flow
     * @param rememberMe                                                the remember me
     * @param requiredActions                                           the required actions
     * @param resetCredentialsFlow                                      the reset credentials flow
     * @param resetPasswordAllowed                                      the reset password
     * @param revokeRefreshToken                                        the revoke refresh token
     * @param roles                                                     the roles
     * @param smtpServers                                               the smtp servers
     * @param sslRequired                                               the ssl required
     * @param ssoSessionIdleTimeout                                     the sso session idle timeout
     * @param ssoSessionIdleTimeoutRememberMe                           the sso session idle timeout remember me
     * @param ssoSessionMaxLifespan                                     the sso session max lifespan
     * @param ssoSessionMaxLifespanRememberMe                           the sso session max lifespan remember me
     * @param supportedLocales                                          the supported locales
     * @param userFederationMappers                                     the user federation mappers
     * @param userFederationProviders                                   the user federation providers
     * @param userManagedAccessAllowed                                  the user managed access allowed
     * @param users                                                     the users
     * @param verifyEmail                                               the verify email
     * @param waitIncrementSeconds                                      the wait increment seconds
     * @param webAuthnPolicyAcceptableAaguids                           the web authn policy acceptable aaguids
     * @param webAuthnPolicyAttestationConveyancePreference             the web authn policy attestation conveyance
     *                                                                  preference
     * @param webAuthnPolicyAuthenticatorAttachment                     the web authn policy authenticator attachment
     * @param webAuthnPolicyAvoidSameAuthenticatorRegister              the web authn policy avoid same authenticator
     *                                                                  register
     * @param webAuthnPolicyCreateTimeout                               the web authn policy create timeout
     * @param webAuthnPolicyPasswordlessAcceptableAaguids               the web authn policy passwordless acceptable
     *                                                                  aaguids
     * @param webAuthnPolicyPasswordlessAttestationConveyancePreference the web authn policy passwordless attestation
     *                                                                  conveyance preference
     * @param webAuthnPolicyPasswordlessAuthenticatorAttachment         the web authn policy passwordless authenticator
     *                                                                  attachment
     * @param webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister  the web authn policy passwordless avoid same
     *                                                                  authenticator register
     * @param webAuthnPolicyPasswordlessCreateTimeout                   the web authn policy passwordless create timeout
     * @param webAuthnPolicyPasswordlessRequireResidentKey              the web authn policy passwordless require
     *                                                                  resident key
     * @param webAuthnPolicyPasswordlessRpEntityName                    the web authn policy passwordless rp entity name
     * @param webAuthnPolicyPasswordlessRpId                            the web authn policy passwordless rp id
     * @param webAuthnPolicyPasswordlessSignatureAlgorithms             the web authn policy passwordless signature
     *                                                                  algorithms
     * @param webAuthnPolicyPasswordlessUserVerificationRequirement     the web authn policy passwordless user
     *                                                                  verification requirement
     * @param webAuthnPolicyRequireResidentKey                          the web authn policy require resident key
     * @param webAuthnPolicyRpEntityName                                the web authn policy rp entity name
     * @param webAuthnPolicyRpId                                        the web authn policy rp id
     * @param webAuthnPolicySignatureAlgorithms                         the web authn policy signature algorithms
     * @param webAuthnPolicyUserVerificationRequirement                 the web authn policy user verification
     *                                                                  requirement
     *
     * @return the realm representation
     */
    @Builder(builderMethodName = "realmBuilder")
    // @formatter:off
    public static RealmRepresentation realmRepresentation(
```

**Comment by McGiverGim** [comment]
Another one here with the same problem but I've not been able to find de culprit:
```
!ENTRY org.eclipse.jdt.core 4 0 2025-02-07 09:50:16.199
!MESSAGE Lombok annotation handler class lombok.eclipse.handlers.HandleData failed
!STACK 0
java.lang.StackOverflowError
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:5000)
	at java.base/java.util.regex.Pattern$LazyLoop.match(Pattern.java:5142)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:5000)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4878)
	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:4134)
	...
```

and 

```
!ENTRY org.eclipse.jdt.core 4 0 2025-02-07 09:50:16.205
!MESSAGE Lombok annotation handler class lombok.eclipse.handlers.HandleConstructor$HandleAllArgsConstructor failed
!STACK 0
java.lang.StackOverflowError
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4914)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4969)
	at java.base/java.util.regex.Pattern$LazyLoop.match(Pattern.java:5146)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:5000)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4878)
	at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:4110)
	...
```

**Comment by Rawi01** [comment]
@McGiverGim You can try to use the build artifact of my linked PR and try if it fixes the problem

**Comment by McGiverGim** [comment]
@Rawi01 I can't find the artifact on the PR. Can you point me to where can I download it?

**Comment by florianhof** [comment]
I had this problem on one project, now solve with the lombok.jar I could locally compile from this branch. Thanks! Hope a release comes soon :-)
